CREATE TABLE Answers (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) FOREIGN KEY REFERENCES Users(id),
  questionId VARCHAR(255) FOREIGN KEY REFERENCES Questions(id),
  comment TEXT,
  date DATETIME,
  accepted INT DEFAULT 0,
);