CREATE TABLE Comments(
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) FOREIGN KEY REFERENCES Users(id) ON DELETE CASCADE,
  answerId VARCHAR(255) FOREIGN KEY REFERENCES Answers(id) ON DELETE CASCADE,
  comment TEXT,
  date DATETIME 
)